name: holbegram
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.1
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1
  firebase_database: ^10.5.1
  uuid: ^4.4.0
  image_picker: ^1.0.5
  cross_file_image: ^1.1.0
  logger: ^2.2.0
  bottom_navy_bar: 6.0.0
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0
  firebase_app_check: ^0.2.2+1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
        - asset: assets/fonts/InstagramSans.ttf
